FORMAT: 1A
HOST: http://therelease.ninja/api

# Release Ninja

Polls is a simple API allowing consumers to view polls and vote in them.

## Projects Collection [/projects]

### List All Projects [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "created_at": "2015-01-31T05:54:40.585Z",
                "title": "Release Ninja",
                "public_header_background": null,
                "public_logo_url": null,
                "public_css": null,
                "slug": "meta",
                "url": "https://meta.therelease.ninja/",
                "robot_token": null,
                "report_url": "https://www.therelease.ninja/plain/3",
                "auto_notify": true,
                "repositories": [
                    {
                    "id": 1,
                    "full_name": "SalesLoft/release-ninja",
                    "url": "https://github.com/SalesLoft/release-ninja"
                    }
                ]
            }
        ]

### Create a New Project [POST]

You may create a new project using this action. It takes a JSON
object containing a title and a collection a repo names which
will be associated and monitored for this project.

+ Request (application/json)

        {
            "title": "Super Cool Project",
            "repos": [
                "sb8244/release-ninja"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /projects/super-cool-project

    + Body

            {
                "id": 1,
                "created_at": "2015-01-31T05:54:40.585Z",
                "title": "Super Cool Project",
                "public_header_background": null,
                "public_logo_url": null,
                "public_css": null,
                "slug": "meta",
                "url": "https://super-cool-project.therelease.ninja/",
                "robot_token": null,
                "report_url": "https://www.therelease.ninja/plain/1",
                "auto_notify": true,
                "repositories": [
                    {
                    "id": 1,
                    "full_name": "sb8244/release-ninja",
                    "url": "https://github.com/sb8244/release-ninja"
                    }
                ]
            }
